### ISSUE TITLE
Issue: error displaying jump states when using yyaxis left/right and 2 plotFlows()

### ISSUE THREAD

**Issue by Ev3nt1ne** [pnanez/HyEQ_Toolbox#101] opened 2024-03-15 10:40 UTC
Error: Warning: Setting the font size and interpreter for ticks is not supported on this version of MATLAB. If you see this warning, please submit an issue on our GitHub repository and include your MATLAB version number. To disable this warning, click here. 
Sample code:
```MATLAB
hpb = HybridPlotBuilder();
hpb.color('g').legend("a").plotFlows(hybrid_arc2.select(3));
hpb.color('g').legend("b ").plotFlows(hybrid_arc2.select(b));
yyaxis right;
hpb.color('r').legend("1").plotFlows(hybrid_arc2.select(1));
hpb.color('b').legend("2").plotFlows(hybrid_arc2.select(2));
yyaxis left;
```

**Comment by Ev3nt1ne** [comment] 2024-03-15 10:41
V. R2021b

**Comment by pwintz** [comment] 2024-04-08 07:50
I was able to reproduce this. Here is an MWE:
```MATLAB
sys = hybrid.examples.BouncingBall();
x0 = [10, 0];
tspan = [0, 20];
jspan = [0, 30];
sol = sys.solve(x0, tspan, jspan);

figure(1); clf
hpb = HybridPlotBuilder(); 
hpb.plotFlows(sol.select(1));
hold on
yyaxis right;
hpb.plot flows(sol.select(2));
yyaxis left;
```
The problem is that this exception is thrown in `HybridPlotBuilder`  

```
MException with properties:
  identifier: 'MATLAB:index:expected_one_output_for_assignment'
     message: 'Assigning to 2 elements using a simple assignment statement is not supported. Consider using comma-separated list assignment.'
       cause: {}
       stack: [3×1 struct]
  Correction: []
```
The source of the exception is this line:
```MATLAB
axes.(axis_name{1}).FontSize = this.settings.tick_label_size;
```
The code was written with the assumption that a`xes.(axis_name{1}).FontSize` would only contain a single value, but because there are axes on both sides, it contains two entries.

I have been able to fix the error by changing the offending lines as follows:
```MATLAB
try
    for axis_name = {'XAxis', 'YAxis', 'ZAxis'}
        % When "yyaxis left;" and "yyaxis right;" are used,
        % then "axes.(axis_name{1})" contains two
        % NumericRulers. Thus, we iterate through each one
        % to set the needed options.
        for ax = axes.(axis_name{1})
            ax.FontSize = this.settings.tick_label_size;
            ax.TickLabelInterpreter = this.settings.tick_label_interpreter;
        end
    end
catch e
    warning('HybridPlotBuilder:UnsupportedOperation:TickSettings', ...
        ['Setting the font size and interpreter for ticks failed with error message "%s".\n' ...
        'If you see this warning, please ' ...
        '<a href="https://github.com/pnanez/HyEQ_Toolbox/issues/new">' ... 
        'submit an issue</a> on our GitHub repository and include your MATLAB version number. ' ...
        'To disable this warning, click <a href="matlab:warning(''off'', ''HybridPlotBuilder:UnsupportedOperation:TickSettings'')">here</a>.'],  e.message)
end
```

I'll include this fix in the next version (whenever that is released).

**Comment by pwintz** [comment] 2024-04-28 02:28
I pushed a fix to `dev`, so the next beta release will contain the fix.

**Closed as completed by pwintz** 2024-04-28 02:28 UTC
Labels: bug, MATLAB
